name: Build and Test

on:
  push:
    branches:
      - main  # You can change this to your main branch name

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you need

    - name: Install project dependencies
      run: |
        pip install -U pip
        pip install .
        if [ ${{ runner.os }} == 'Windows' ]; then pip install nuitka; fi

    - name: Build binary (if on Windows)
      run: |
        if [ ${{ runner.os }} == 'Windows' ]; then
          python -m nuitka --follow-imports --onefile --enable-console contacts_birthdays.py --output-filename="contacts_birthdays.exe"
        fi

    - name: Build docs
      run: |
        python build.py build-docs

    - name: Run tests (if you have tests)
      run: |
        python -m pytest

    - name: Upload binary artifact
      if: ${{ runner.os }} == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: binary-artifact
        path: contacts_birthdays.exe

    - name: Upload docs artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs-artifact
        path: ./docs
