name: Build Project

on:
  push:
    branches:
      - main  # You can change this to your main branch name

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Choose the Python version you need

    - name: Install dependencies
      run: pip install -U pip
      continue-on-error: true

    - name: Build project
      run: python build.py --build-binary
      continue-on-error: true

    - name: Upload binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary-artifact
        path: ./path/to/your/binary/executable  # Replace with the path to your binary
